-- ================== USERS ==================
CREATE TABLE users
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username       TEXT        NOT NULL UNIQUE,
    password       TEXT,
    first_name     TEXT,
    last_name      TEXT,
    email          TEXT,
    favorite_genre TEXT,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================== MEDIA ==================
CREATE TABLE media
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title           TEXT        NOT NULL,
    description     TEXT,
    media_type      TEXT        NOT NULL,
    release_year    TEXT,
    age_restriction SMALLINT    NOT NULL DEFAULT 0,
    created_by      BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Media genres as tags
CREATE TABLE media_genres
(
    media_id BIGINT NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    genre    TEXT   NOT NULL,
    PRIMARY KEY (media_id, genre)
);

-- ================== RATINGS ==================
CREATE TABLE ratings
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    media_id             BIGINT      NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    user_id              BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    stars                SMALLINT    NOT NULL,
    comment              TEXT,
    is_comment_confirmed BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Likes on ratings (one like per user per rating)
CREATE TABLE rating_likes
(
    rating_id  BIGINT      NOT NULL REFERENCES ratings (id) ON DELETE CASCADE,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (rating_id, user_id)
);

-- ================== FAVORITES ==================
CREATE TABLE favorites
(
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    media_id   BIGINT      NOT NULL REFERENCES media (id) ON DELETE CASCADE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, media_id)
);

-- ================== MEDIA SCORE ==================

ALTER TABLE media
    ADD COLUMN score NUMERIC(3, 2) NOT NULL DEFAULT 0;


CREATE
OR REPLACE FUNCTION recompute_media_score(p_media_id BIGINT)
RETURNS VOID
LANGUAGE sql
AS $$
UPDATE media m
SET score =
        COALESCE(
                (SELECT ROUND(AVG(r.stars)::numeric, 2)
                 FROM ratings r
                 WHERE r.media_id = p_media_id
                   AND r.is_comment_confirmed = TRUE),
                0
        )
WHERE m.id = p_media_id;
$$;

CREATE
OR REPLACE FUNCTION trg_ratings_recompute_media_score()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  IF
TG_OP = 'INSERT' THEN
    PERFORM recompute_media_score(NEW.media_id);
RETURN NEW;
ELSIF
TG_OP = 'UPDATE' THEN
    -- If someone moves a rating to another media, recompute both
    IF NEW.media_id IS DISTINCT FROM OLD.media_id THEN
      PERFORM recompute_media_score(OLD.media_id);
      PERFORM
recompute_media_score(NEW.media_id);
ELSE
      -- Only recompute when score-relevant fields changed
      IF NEW.stars IS DISTINCT FROM OLD.stars
         OR NEW.is_comment_confirmed IS DISTINCT FROM OLD.is_comment_confirmed THEN
        PERFORM recompute_media_score(NEW.media_id);
END IF;
END IF;

RETURN NEW;
ELSIF
TG_OP = 'DELETE' THEN
    PERFORM recompute_media_score(OLD.media_id);
RETURN OLD;
END IF;

RETURN NULL;
END;
$$;

DROP TRIGGER IF EXISTS ratings_recompute_media_score ON ratings;

CREATE TRIGGER ratings_recompute_media_score
    AFTER INSERT OR
UPDATE OR
DELETE
ON ratings
    FOR EACH ROW
    EXECUTE FUNCTION trg_ratings_recompute_media_score();

