-- ================== USERS ==================
CREATE TABLE users (
                       id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username      TEXT NOT NULL UNIQUE,
                       password      TEXT,
                       first_name    TEXT,
                       last_name     TEXT,
                       email         TEXT,
                       favorite_genre         TEXT,
                       created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- ================== MEDIA ==================
CREATE TABLE media (
                       id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title              TEXT NOT NULL,
                       description        TEXT,
                       media_type         TEXT NOT NULL,
                       release_year       TEXT,
                       age_restriction    SMALLINT NOT NULL DEFAULT 0,
                       created_by         BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                       created_at         TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Media genres as tags
CREATE TABLE media_genres (
                              media_id BIGINT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
                              genre    TEXT   NOT NULL,
                              PRIMARY KEY (media_id, genre)
);

-- ================== RATINGS ==================
CREATE TABLE ratings (
                         id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         media_id              BIGINT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
                         user_id               BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                         stars                 SMALLINT NOT NULL,
                         comment               TEXT,
                         is_comment_confirmed  BOOLEAN NOT NULL DEFAULT FALSE,
                         created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Likes on ratings (one like per user per rating)
CREATE TABLE rating_likes (
                              rating_id BIGINT NOT NULL REFERENCES ratings(id) ON DELETE CASCADE,
                              user_id   BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                              created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                              PRIMARY KEY (rating_id, user_id)
);

-- ================== FAVORITES ==================
CREATE TABLE favorites (
                           user_id  BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                           media_id BIGINT NOT NULL REFERENCES media(id) ON DELETE CASCADE,
                           created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                           PRIMARY KEY (user_id, media_id)
);


